# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97fbd8f6e07a329918fb49b122f35713f641589c4df06f3372c6fb6fd3aea0b817aed553e6bfac5b5d3ea38b896da06e05a1fcff604871dffa9ed191abb272dc

test:
  secret_key_base: 6b362bc32cb1a6ffa65cee3040e5ca3d05a0ff6b0031b9898694fac57e10bfda468fd2798cf064085232d17653622b05faafa083ca777add8114c0757c680b6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
